package com.kolpolok.nord.helpers

import android.content.Context
import android.telephony.TelephonyManager
import com.kolpolok.nord.R

object CountryUtils {
    fun getFlagImage(countryCode: String?): Int {
        return when (countryCode) {
            "004" -> R.drawable.flag_afghanistan
            "008" -> R.drawable.flag_albania
            "012" -> R.drawable.flag_algeria
            "020" -> R.drawable.flag_andorra
            "024" -> R.drawable.flag_angola
            "010" -> R.drawable.flag_antarctica
            "032" -> R.drawable.flag_argentina
            "051" -> R.drawable.flag_armenia
            "533" -> R.drawable.flag_aruba
            "036" -> R.drawable.flag_australia
            "040" -> R.drawable.flag_austria
            "031" -> R.drawable.flag_azerbaijan
            "048" -> R.drawable.flag_bahrain
            "050" -> R.drawable.flag_bangladesh
            "112" -> R.drawable.flag_belarus
            "056" -> R.drawable.flag_belgium
            "084" -> R.drawable.flag_belize
            "204" -> R.drawable.flag_benin
            "064" -> R.drawable.flag_bhutan
            "068" -> R.drawable.flag_bolivia
            "070" -> R.drawable.flag_bosnia
            "072" -> R.drawable.flag_botswana
            "076" -> R.drawable.flag_brazil
            "096" -> R.drawable.flag_brunei
            "100" -> R.drawable.flag_bulgaria
            "854" -> R.drawable.flag_burkina_faso
            "104" -> R.drawable.flag_myanmar
            "108" -> R.drawable.flag_burundi
            "116" -> R.drawable.flag_cambodia
            "120" -> R.drawable.flag_cameroon
            "124" -> R.drawable.flag_canada
            "132" -> R.drawable.flag_cape_verde
            "140" -> R.drawable.flag_central_african_republic
            "148" -> R.drawable.flag_chad
            "152" -> R.drawable.flag_chile
            "156" -> R.drawable.flag_china
            "170" -> R.drawable.flag_colombia
            "174" -> R.drawable.flag_comoros
            "178" -> R.drawable.flag_republic_of_the_congo
            "180" -> R.drawable.flag_democratic_republic_of_the_congo
            "184" -> R.drawable.flag_cook_islands
            "188" -> R.drawable.flag_costa_rica
            "191" -> R.drawable.flag_croatia
            "192" -> R.drawable.flag_cuba
            "196" -> R.drawable.flag_cyprus
            "203" -> R.drawable.flag_czech_republic
            "208" -> R.drawable.flag_denmark
            "262" -> R.drawable.flag_djibouti
            "626" -> R.drawable.flag_timor_leste
            "218" -> R.drawable.flag_ecuador
            "818" -> R.drawable.flag_egypt
            "222" -> R.drawable.flag_el_salvador
            "226" -> R.drawable.flag_equatorial_guinea
            "232" -> R.drawable.flag_eritrea
            "233" -> R.drawable.flag_estonia
            "231" -> R.drawable.flag_ethiopia
            "238" -> R.drawable.flag_falkland_islands
            "234" -> R.drawable.flag_faroe_islands
            "242" -> R.drawable.flag_fiji
            "246" -> R.drawable.flag_finland
            "250" -> R.drawable.flag_france
            "258" -> R.drawable.flag_french_polynesia
            "266" -> R.drawable.flag_gabon
            "270" -> R.drawable.flag_gambia
            "268" -> R.drawable.flag_georgia
            "276" -> R.drawable.flag_germany
            "288" -> R.drawable.flag_ghana
            "292" -> R.drawable.flag_gibraltar
            "300" -> R.drawable.flag_greece
            "304" -> R.drawable.flag_greenland
            "320" -> R.drawable.flag_guatemala
            "324" -> R.drawable.flag_guinea
            "624" -> R.drawable.flag_guinea_bissau
            "328" -> R.drawable.flag_guyana
            "gf" -> R.drawable.flag_guyane
            "332" -> R.drawable.flag_haiti
            "340" -> R.drawable.flag_honduras
            "344" -> R.drawable.flag_hong_kong
            "348" -> R.drawable.flag_hungary
            "356" -> R.drawable.flag_india
            "360" -> R.drawable.flag_indonesia
            "364" -> R.drawable.flag_iran
            "368" -> R.drawable.flag_iraq
            "372" -> R.drawable.flag_ireland
            "833" -> R.drawable.flag_isleof_man
            "376" -> R.drawable.flag_israel
            "380" -> R.drawable.flag_italy
            "384" -> R.drawable.flag_cote_divoire
            "392" -> R.drawable.flag_japan
            "400" -> R.drawable.flag_jordan
            "398" -> R.drawable.flag_kazakhstan
            "404" -> R.drawable.flag_kenya
            "296" -> R.drawable.flag_kiribati
            "414" -> R.drawable.flag_kuwait
            "417" -> R.drawable.flag_kyrgyzstan
            "136" -> R.drawable.flag_cayman_islands
            "418" -> R.drawable.flag_laos
            "428" -> R.drawable.flag_latvia
            "422" -> R.drawable.flag_lebanon
            "426" -> R.drawable.flag_lesotho
            "430" -> R.drawable.flag_liberia
            "434" -> R.drawable.flag_libya
            "438" -> R.drawable.flag_liechtenstein
            "440" -> R.drawable.flag_lithuania
            "442" -> R.drawable.flag_luxembourg
            "446" -> R.drawable.flag_macao
            "450" -> R.drawable.flag_madagascar
            "454" -> R.drawable.flag_malawi
            "458" -> R.drawable.flag_malaysia
            "462" -> R.drawable.flag_maldives
            "466" -> R.drawable.flag_mali
            "470" -> R.drawable.flag_malta
            "584" -> R.drawable.flag_marshall_islands
            "478" -> R.drawable.flag_mauritania
            "480" -> R.drawable.flag_mauritius
            "474" -> R.drawable.flag_martinique
            "484" -> R.drawable.flag_mexico
            "583" -> R.drawable.flag_micronesia
            "498" -> R.drawable.flag_moldova
            "492" -> R.drawable.flag_monaco
            "496" -> R.drawable.flag_mongolia
            "499" -> R.drawable.flag_of_montenegro // custom
            "504" -> R.drawable.flag_morocco
            "508" -> R.drawable.flag_mozambique
            "516" -> R.drawable.flag_namibia
            "520" -> R.drawable.flag_nauru
            "524" -> R.drawable.flag_nepal
            "528" -> R.drawable.flag_netherlands
            "540" -> R.drawable.flag_new_caledonia
            "554" -> R.drawable.flag_new_zealand
            "558" -> R.drawable.flag_nicaragua
            "562" -> R.drawable.flag_niger
            "566" -> R.drawable.flag_nigeria
            "570" -> R.drawable.flag_niue
            "410" -> R.drawable.flag_north_korea
            "578" -> R.drawable.flag_norway
            "512" -> R.drawable.flag_oman
            "586" -> R.drawable.flag_pakistan
            "585" -> R.drawable.flag_palau
            "591" -> R.drawable.flag_panama
            "598" -> R.drawable.flag_papua_new_guinea
            "600" -> R.drawable.flag_paraguay
            "604" -> R.drawable.flag_peru
            "608" -> R.drawable.flag_philippines
            "612" -> R.drawable.flag_pitcairn_islands
            "616" -> R.drawable.flag_poland
            "620" -> R.drawable.flag_portugal
            "630" -> R.drawable.flag_puerto_rico
            "634" -> R.drawable.flag_qatar
            "642" -> R.drawable.flag_romania
            "643" -> R.drawable.flag_russian_federation
            "646" -> R.drawable.flag_rwanda
            "652" -> R.drawable.flag_saint_barthelemy // custom
            "882" -> R.drawable.flag_samoa
            "674" -> R.drawable.flag_san_marino
            "678" -> R.drawable.flag_sao_tome_and_principe
            "682" -> R.drawable.flag_saudi_arabia
            "686" -> R.drawable.flag_senegal
            "688" -> R.drawable.flag_serbia // custom
            "690" -> R.drawable.flag_seychelles
            "694" -> R.drawable.flag_sierra_leone
            "702" -> R.drawable.flag_singapore
            "703" -> R.drawable.flag_slovakia
            "705" -> R.drawable.flag_slovenia
            "090" -> R.drawable.flag_soloman_islands
            "706" -> R.drawable.flag_somalia
            "710" -> R.drawable.flag_south_africa
            "408" -> R.drawable.flag_south_korea
            "724" -> R.drawable.flag_spain
            "144" -> R.drawable.flag_sri_lanka
            "654" -> R.drawable.flag_saint_helena // custom
            "666" -> R.drawable.flag_saint_pierre
            "729" -> R.drawable.flag_sudan
            "740" -> R.drawable.flag_suriname
            "752" -> R.drawable.flag_sweden
            "756" -> R.drawable.flag_switzerland
            "760" -> R.drawable.flag_syria
            "158" -> R.drawable.flag_taiwan
            "762" -> R.drawable.flag_tajikistan
            "834" -> R.drawable.flag_tanzania
            "764" -> R.drawable.flag_thailand
            "768" -> R.drawable.flag_togo
            "772" -> R.drawable.flag_tokelau
            "776" -> R.drawable.flag_tonga
            "788" -> R.drawable.flag_tunisia
            "792" -> R.drawable.flag_turkey
            "795" -> R.drawable.flag_turkmenistan
            "798" -> R.drawable.flag_tuvalu
            "784" -> R.drawable.flag_uae
            "800" -> R.drawable.flag_uganda
            "826" -> R.drawable.flag_united_kingdom
            "804" -> R.drawable.flag_ukraine
            "858" -> R.drawable.flag_uruguay
            "840" -> R.drawable.flag_united_states_of_america
            "860" -> R.drawable.flag_uzbekistan
            "548" -> R.drawable.flag_vanuatu
            "862" -> R.drawable.flag_venezuela
            "704" -> R.drawable.flag_vietnam
            "876" -> R.drawable.flag_wallis_and_futuna
            "887" -> R.drawable.flag_yemen
            "894" -> R.drawable.flag_zambia
            "716" -> R.drawable.flag_zimbabuwe
            "660" -> R.drawable.flag_anguilla
            "028" -> R.drawable.flag_antigua_and_barbuda
            "044" -> R.drawable.flag_bahamas
            "052" -> R.drawable.flag_barbados
            "bm" -> R.drawable.flag_bermuda
            "092" -> R.drawable.flag_british_virgin_islands
            "212" -> R.drawable.flag_dominica
            "214" -> R.drawable.flag_dominican_republic
            "308" -> R.drawable.flag_grenada
            "388" -> R.drawable.flag_jamaica
            "500" -> R.drawable.flag_montserrat
            "659" -> R.drawable.flag_saint_kitts_and_nevis
            "662" -> R.drawable.flag_saint_lucia
            "670" -> R.drawable.flag_saint_vicent_and_the_grenadines
            "780" -> R.drawable.flag_trinidad_and_tobago
            "796" -> R.drawable.flag_turks_and_caicos_islands
            "850" -> R.drawable.flag_us_virgin_islands
            "728" -> R.drawable.flag_south_sudan
            else -> R.drawable.no_image
        }
    }

    fun getDeviceCountryCode(context: Context): String {
        val tm = context.getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
        return tm.networkCountryIso
    }
}